### ISSUE TITLE
CSS does not specify fallback if Inconsolata is unavailable

### ISSUE THREAD

**Issue by wezm** [steadylearner/Python-Blog#1]
If the Inconsolata font fails to load for some reason (like it did for me) the CSS doesn't fall back to the default monospace font, which results in the code examples looking like this:

![image](https://user-images.githubusercontent.com/21787/73589722-50861c80-452e-11ea-9146-5fb4e5559e33.png)

I think this line

https://github.com/steadylearner/Python-Blog/blob/26d4fb8a7d195dd1e0678b2ce93beb6fd74b3723/static/markdown.css#L365

Should be something like:

```css
font-family: Inconsolata, monospace;
```

**Comment by steadylearner** [comment]
Sorry for the late response and thanks for pointing the part to help others.

I am planning to move these Python files and manage at the [Rust Full Stack](https://github.com/steadylearner/Rust-Full-Stack) repository.

I will maintain this also with a link for it. If you need a help, please contact me.
